### ISSUE TITLE
Unable to run the training command specified in the readme.

### ISSUE THREAD

**Issue by amarchia** [patrik-ha/explainable-minichess#5]
When I run "python -m minichess.rl.fast_mcts configs/base.json" (without the quotes), I get a FileNotFoundError.

FileNotFoundError: [Errno 2] No such file or directory: '/explainable-minichess/minichess/chess/magics/5x4/straights.npz'.

I am trying to reproduce your training setup for 5x4, though I'd eventually like to get 8x8 running as well.

**Comment by patrik-ha** [comment]
I couldn't reproduce the issue on a fresh clone of the repo myself, but I have an idea of what the issue could be. I've pushed a suspected fix for that, let me know if it works for you now. 

Regarding training on 8x8 chess, I don't think that it is possible/practical to use this repo to train for "normal" chess. The main thing is that this repo is optimised for situations where one has small models able to provide inference on each thread relatively quickly while generating self-play games for the Monte Carlo Tree Search procedure. For larger chess variants you would probably need a larger model, and it would most likely be too slow to expect each thread to do inference with the model on the CPU for each running game. I would suggest looking at something like https://github.com/deepmind/mctx and implementing chess for that (might be a lot of work), or [the Leela Chess project](https://github.com/LeelaChessZero/) where they train their models collaboratively, depending on what you want to do.

**Comment by amarchia** [comment]
Thank you very much for your fix here. It did work for me and I have 5x6 training now. I'm not sure if a super deep network is necessary for what I'm interested in testing out.
